---
# Task to init MacOS distribution

- name: Install and configure MacOS
  ansible.builtin.include_role:
    name: '{{ role }}'
  loop:
    - common
    - brew
    - ohmyzsh
  loop_control:
    loop_var: role
