---
# This is the main file to start the installation and autoselect the OS distribution.

- name: Determine OS and run appropriate playbook
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Distribution is MacOS
      import_tasks: distribution_macos.yml
      when: ansible_distribution == "MacOSX"

    # - name: Distribution is Fedora
    #   import_tasks: distribution_fedora.yml
    #   when: ansible_distribution == "Fedora"
