---
# file: roles/fedora/tasks/main.yml

- name: Add rpmfusion free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Add rpmfusion none free
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Update and upgrade system
  dnf: name=* state=latest
  tags: update
  ignore_errors: yes
