# ---
# # file: roles/macos/tasks/brew.yml

- name: Install MacOS Packages
  become: false
  block:
    - name: Upgrading Homebrew Packages (always as changed with check mode)
      homebrew:
        upgrade_all: true
      register: result
      until: result is successful

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ macos['brew']['cask_packages'] }}"
        state: present
      register: result
      until: result is successful

    - name: Installing Homebrew Packages 
      homebrew:
        name: "{{ macos['brew']['packages'] }}"
        state: present
      register: result
      until: result is successful
