# ---
# Install homebrew and a list of packages and casks

- name: Install MacOS Packages
  become: false
  block:
    - name: Upgrading Homebrew Packages (always as changed with check mode)
      community.general.homebrew:
        upgrade_all: true
      register: result
      until: result is successful

    - name: Installing Homebrew Cask Packages
      community.general.homebrew_cask:
        name: "{{ macos['brew']['cask_packages'] }}"
        state: present
        greedy: true
        install_options: force
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      community.general.homebrew:
        name: "{{ macos['brew']['packages'] }}"
        state: present
      register: result
      until: result is successful

    - name: Find all task files
      find:
        paths: "{{ role_path }}/tasks"
        patterns: "*.yml"
        excludes: "main.yml"
      register: task_files

    - name: Include all task files
      include_tasks: "{{ item.path }}"
      with_items: "{{ task_files.files }}"
