# ---
# Uses: git, zsh

- name: Install Oh My Zsh
  become: false
  block:
    - name: Check if ~/.oh-my-zsh directory exists
      ansible.builtin.stat:
        path: "/Users/{{ ansible_env.USER }}/.oh-my-zsh"
      register: dir_ohmyzsh

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
      when: not dir_ohmyzsh.stat.exists

    - name: Run Oh My Zsh installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
      when: not dir_ohmyzsh.stat.exists

    - name: Remove Oh My Zsh installation script
      ansible.builtin.file:
        path: /tmp/install_ohmyzsh.sh
        state: absent
      when: not dir_ohmyzsh.stat.exists

    - name: Download powerline-fonts repository
      ansible.builtin.git:
        repo: 'https://github.com/powerline/fonts.git'
        dest: /tmp/powerline-fonts
        depth: 1

    - name: Run powerline-fonts installation script
      command: sh /tmp/fonts/install.sh --unattended
      register: fonts_result
      failed_when: "'FAILED' in fonts_result.stderr"

    - name: Remove powerline-fonts installation script
      ansible.builtin.file:
        path: /tmp/powerline-fonts
        state: absent
