---
# Common tasks for all Unix OSes

- name: NOPASSWD sudo
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ ansible_env.SUDO_USER }}
    owner: root
    group: wheel
    mode: '0440'
