---
# Common tasks for all Unix OSes

- name: NOPASSWD sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_env.SUDO_USER }}
    create: yes
    state: present
    owner: root
    group: root
    mode: '0440'
    line: '{{ ansible_env.USERNAME }} ALL=(ALL) NOPASSWD: ALL'
